name: laravel-site
type: laravel
docroot: public
php_version: "8.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mysql
  version: "8.0"
nodejs_version: "20"
hooks:
  post-start:
    - exec: "if [ ! -f artisan ]; then composer create-project --prefer-dist laravel/laravel:^11.0 . && chmod -R 775 storage bootstrap/cache; fi"
composer_version: "2" 